# 🔢 NumPy — Numerical Python

> **Step 2: Data Science**  
> **Library 01: NumPy**  
> **Class 17 — NumPy Fundamentals**

NumPy is the first major Python library in my Data Science journey.

It provides powerful tools for numerical computing, arrays, mathematical operations, statistics, linear algebra, and efficient data processing.

---
# 🎯 What is NumPy?

**NumPy** stands for:

> **Numerical Python**

It is one of the most important Python libraries for:

- Numerical computing
- Working with arrays
- Mathematical operations
- Statistical calculations
- Linear algebra
- Data manipulation
- Scientific computing
- Machine Learning
- Deep Learning
- Data Science

NumPy provides a powerful data structure called the:

> **NumPy Array (`ndarray`)**

Example:

In [10]:
pip install numpy


[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [11]:
# pip install numpy   (run once if NumPy is not installed)
import numpy as np

print("NumPy version:", np.__version__)

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)

NumPy version: 2.5.3
[10 20 30 40 50]


Output:

```text
[10 20 30 40 50]
```

---
# 🚀 Why Learn NumPy?

Before working with Pandas, Machine Learning, Deep Learning, and many other tools, it is important to understand NumPy.

NumPy provides the foundation for numerical operations in Python.

It is commonly used in:

```text
NumPy
   ↓
Pandas
   ↓
Data Science
   ↓
Machine Learning
   ↓
Deep Learning
   ↓
AI
```

Many popular Python libraries use NumPy internally or work closely with NumPy arrays.

---
# 📚 What I Will Learn

### NumPy Fundamentals
* What is NumPy?
* Why NumPy is used
* Installing NumPy
* Importing NumPy
* NumPy version
* Creating NumPy arrays
* Python lists vs NumPy arrays
* One-dimensional, two-dimensional and multi-dimensional arrays
* `ndarray`

### Array Properties
* `ndim`, `shape`, `size`, `dtype`, `itemsize`

### Creating Arrays
* `np.array()`, `np.zeros()`, `np.ones()`, `np.empty()`, `np.full()`, `np.arange()`, `np.linspace()`, `np.eye()`
* Random arrays

### Array Indexing
* Positive indexing
* Negative indexing
* Multi-dimensional indexing
* Row and column access
* Selecting individual values

### Array Slicing
* One-dimensional slicing
* Two-dimensional slicing
* Row slicing
* Column slicing
* Step slicing
* Reverse slicing

### Array Data Types
* Integer, Float, Boolean, String
* `dtype`
* Converting data types
* `astype()`

### Mathematical Operations
* Addition, Subtraction, Multiplication, Division
* Power, Modulus, Absolute values
* Square root, Exponential, Logarithms
* Trigonometric functions

### Statistical Operations
* Sum, Mean, Median, Minimum, Maximum
* Standard deviation, Variance, Percentiles
* Minimum/maximum index

### Array Operations
* Addition, subtraction, multiplication, division between arrays
* Comparison operations
* Boolean operations

### Broadcasting
* What broadcasting means
* Broadcasting rules
* Broadcasting with scalars
* Broadcasting between arrays

### Reshaping Arrays
* `reshape()`, Flattening, `flatten()`, `ravel()`, Transpose, `T`

### Joining Arrays
* `concatenate()`, `stack()`, `vstack()`, `hstack()`

### Splitting Arrays
* `split()`, `vsplit()`, `hsplit()`

### Copy and View
* Array references
* Copy
* View
* Difference between copy and view

### Sorting
* `sort()`
* Sorting arrays
* Sorting along an axis

### Searching
* `where()`
* Searching values
* Finding indexes
* Filtering arrays

### Boolean Filtering
* Boolean conditions
* Boolean masks
* Filtering values
* Multiple conditions

### Random Numbers
* Random numbers, integers, floats, arrays
* Random seeds
* Reproducibility

### Linear Algebra
* Dot product
* Matrix multiplication
* Transpose
* Determinant
* Inverse
* Matrix operations

### Practical NumPy
* Working with numerical datasets
* Data preprocessing
* Normalization
* Standardization
* Feature arrays
* Handling missing values
* Preparing data for Machine Learning

---
# 🧠 NumPy Array

The most important concept in NumPy is the **array**.

A NumPy array is a collection of values stored in a structured numerical format.

In [12]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)
print(type(numbers))

[10 20 30 40 50]
<class 'numpy.ndarray'>


---
# 📊 Python List vs NumPy Array

Python list:

```python
numbers = [10, 20, 30, 40, 50]
```

NumPy array:

```python
numbers = np.array([10, 20, 30, 40, 50])
```

NumPy arrays are designed for numerical operations and can perform many calculations more efficiently and conveniently than normal Python lists.

In [13]:
py_list = [10, 20, 30, 40, 50]
np_array = np.array([10, 20, 30, 40, 50])

# Multiplying a list REPEATS it; multiplying an array does MATH on each element
print("List  * 2 :", py_list * 2)
print("Array * 2 :", np_array * 2)

List  * 2 : [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
Array * 2 : [ 20  40  60  80 100]


---
# 📐 Dimensions of Arrays

NumPy arrays can have different dimensions.

## 1D Array

In [14]:
a1 = np.array([1, 2, 3, 4])
print(a1)

[1 2 3 4]


## 2D Array

This can be thought of as:

```text
Rows × Columns

2 × 3
```

In [15]:
a2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(a2)

[[1 2 3]
 [4 5 6]]


## 3D Array

3D arrays are useful when working with more complex numerical structures such as image data.

In [16]:
a3 = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
print(a3)
print("Shape:", a3.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


---
# 🔍 Important Array Properties

NumPy provides useful properties for understanding an array.

In [17]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("ndim    :", data.ndim)
print("shape   :", data.shape)
print("size    :", data.size)
print("dtype   :", data.dtype)
print("itemsize:", data.itemsize)

ndim    : 2
shape   : (2, 3)
size    : 6
dtype   : int64
itemsize: 8


| Property   | Meaning                     |
| ---------- | --------------------------- |
| `ndim`     | Number of dimensions        |
| `shape`    | Size of each dimension      |
| `size`     | Total number of elements    |
| `dtype`    | Data type of elements       |
| `itemsize` | Memory size of each element |

---
# 🏗️ Creating NumPy Arrays

NumPy provides many functions for creating arrays.

## `np.array()`

In [18]:
numbers = np.array([1, 2, 3, 4, 5])
print(numbers)

[1 2 3 4 5]


## `np.zeros()`

In [19]:
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


Output:

```text
[0. 0. 0. 0. 0.]
```

## `np.ones()`

In [20]:
ones = np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


## `np.empty()`

Creates an array **without initialising values** — the contents are whatever was in memory, so don't rely on them.

In [21]:
empty = np.empty(3)
print(empty)

[3. 2. 1.]


## `np.full()`

In [22]:
numbers = np.full(5, 10)
print(numbers)

[10 10 10 10 10]


Output:

```text
[10 10 10 10 10]
```

## `np.arange()`

In [23]:
numbers = np.arange(1, 10)
print(numbers)

[1 2 3 4 5 6 7 8 9]


Output:

```text
[1 2 3 4 5 6 7 8 9]
```

## `np.linspace()`

This creates evenly spaced values between two numbers.

In [24]:
numbers = np.linspace(0, 10, 5)
print(numbers)

[ 0.   2.5  5.   7.5 10. ]


## `np.eye()`

Creates an identity matrix.

In [25]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


---
# 🎯 Indexing

NumPy supports indexing similar to Python lists.

In [26]:
numbers = np.array([10, 20, 30, 40, 50])

print(numbers[0])
print(numbers[2])
print(numbers[-1])

10
30
50


Output:

```text
10
30
50
```

### Multi-dimensional indexing

In [27]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(data[1, 2])   # row 1, column 2 -> 60
print(data[0])      # first row
print(data[:, 1])   # second column

60
[10 20 30]
[20 50 80]


---
# ✂️ Slicing

NumPy supports slicing.

In [28]:
numbers = np.array([10, 20, 30, 40, 50])

print(numbers[1:4])
print(numbers[::2])    # step slicing
print(numbers[::-1])   # reverse slicing

[20 30 40]
[10 30 50]
[50 40 30 20 10]


Output of `numbers[1:4]`:

```text
[20 30 40]
```

For a 2D array:

In [29]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(data[0:2, 1:3])

[[20 30]
 [50 60]]


---
# 🔤 Array Data Types

In [30]:
ints   = np.array([1, 2, 3])
floats = np.array([1.5, 2.5, 3.5])
bools  = np.array([True, False, True])
strs   = np.array(["a", "b", "c"])

print(ints.dtype, floats.dtype, bools.dtype, strs.dtype)

# Converting data types with astype()
print(floats.astype(int))
print(ints.astype(float))

int64 float64 bool <U1
[1 2 3]
[1. 2. 3.]


---
# ➕ Mathematical Operations

NumPy makes numerical calculations simple.

In [31]:
numbers = np.array([10, 20, 30, 40])

print(numbers + 10)
print(numbers - 5)
print(numbers * 2)
print(numbers / 10)

[20 30 40 50]
[ 5 15 25 35]
[20 40 60 80]
[1. 2. 3. 4.]


Output:

```text
[20 30 40 50]
[ 5 15 25 35]
[20 40 60 80]
[1. 2. 3. 4.]
```

### More math functions

In [32]:
x = np.array([1, 4, 9, 16])

print(x ** 2)          # power
print(x % 3)           # modulus
print(np.abs(np.array([-3, -1, 2])))
print(np.sqrt(x))
print(np.exp(np.array([0, 1, 2])))
print(np.log(np.array([1, np.e, np.e**2])))
print(np.sin(np.array([0, np.pi/2, np.pi])))

[  1  16  81 256]
[1 1 0 1]
[3 1 2]
[1. 2. 3. 4.]
[1.         2.71828183 7.3890561 ]
[0. 1. 2.]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]


---
# 📊 Statistical Functions

NumPy provides many statistical functions. These operations are extremely important in Data Science.

In [33]:
data = np.array([10, 20, 30, 40, 50])

print("Sum      :", np.sum(data))
print("Mean     :", np.mean(data))
print("Median   :", np.median(data))
print("Min      :", np.min(data))
print("Max      :", np.max(data))
print("Std Dev  :", np.std(data))
print("Variance :", np.var(data))
print("75th pct :", np.percentile(data, 75))
print("Argmin   :", np.argmin(data))
print("Argmax   :", np.argmax(data))

Sum      : 150
Mean     : 30.0
Median   : 30.0
Min      : 10
Max      : 50
Std Dev  : 14.142135623730951
Variance : 200.0
75th pct : 40.0
Argmin   : 0
Argmax   : 4


---
# 🔁 Operations Between Arrays

In [34]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)
print(b - a)
print(a * b)
print(b / a)

# Comparison and Boolean operations
print(a > 1)
print(np.logical_and(a > 1, b < 30))

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[False  True  True]
[False  True False]


---
# 🎯 Boolean Filtering

NumPy can filter data using conditions. This concept becomes very important later when working with Pandas and datasets.

In [35]:
numbers = np.array([10, 20, 30, 40, 50])

result = numbers[numbers > 25]

print(result)

[30 40 50]


Output:

```text
[30 40 50]
```

### Multiple conditions

In [36]:
mask = (numbers > 15) & (numbers < 45)
print(mask)
print(numbers[mask])

[False  True  True  True False]
[20 30 40]


---
# 🔎 Searching and Sorting

In [37]:
arr = np.array([40, 10, 30, 20, 50])

print(np.sort(arr))
print(np.where(arr > 25))              # indexes where condition is True
print(np.where(arr > 25, "big", "small"))

m = np.array([[3, 1, 2], [9, 7, 8]])
print(np.sort(m, axis=1))              # sort each row

[10 20 30 40 50]
(array([0, 2, 4]),)
['big' 'small' 'big' 'small' 'big']
[[1 2 3]
 [7 8 9]]


---
# 📐 Reshaping

An array can be reshaped into another structure. The number of elements must remain the same.

In [38]:
numbers = np.arange(1, 7)

matrix = numbers.reshape(2, 3)

print(matrix)

[[1 2 3]
 [4 5 6]]


Output:

```text
[[1 2 3]
 [4 5 6]]
```

### Flattening

In [39]:
print(matrix.flatten())   # always returns a copy
print(matrix.ravel())     # returns a view when possible

[1 2 3 4 5 6]
[1 2 3 4 5 6]


---
# 🔄 Transpose

Transpose changes rows into columns and columns into rows.

In [40]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix.T)

[[1 4]
 [2 5]
 [3 6]]


Output:

```text
[[1 4]
 [2 5]
 [3 6]]
```

---
# 📡 Broadcasting

Broadcasting allows NumPy to perform operations between arrays with compatible shapes.

The value `5` below is automatically applied to every element.

In [41]:
numbers = np.array([10, 20, 30])

print(numbers + 5)

[15 25 35]


Output:

```text
[15 25 35]
```

### Broadcasting between arrays

In [42]:
col = np.array([[1], [2], [3]])   # shape (3, 1)
row = np.array([10, 20, 30])      # shape (3,)

print(col + row)                  # result shape (3, 3)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


Broadcasting is an important NumPy concept for Machine Learning and numerical computing.

---
# 🔗 Joining and ✂️ Splitting Arrays

In [43]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.concatenate([a, b]))
print(np.stack([a, b]))
print(np.vstack([a, b]))
print(np.hstack([a, b]))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [44]:
arr = np.arange(1, 9)
print(np.split(arr, 4))

m = np.arange(1, 17).reshape(4, 4)
print(np.vsplit(m, 2))
print(np.hsplit(m, 2))

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


---
# 📎 Copy and View

In [45]:
original = np.array([1, 2, 3, 4])

v = original.view()   # shares memory
c = original.copy()   # independent

original[0] = 99

print("original:", original)
print("view    :", v)   # changed too
print("copy    :", c)   # unchanged

original: [99  2  3  4]
view    : [99  2  3  4]
copy    : [1 2 3 4]


---
# 🎲 Random Numbers

NumPy also provides tools for generating random numbers.

In [46]:
numbers = np.random.randint(1, 100, 5)

print(numbers)

[62 74 56 94  1]


Example output:

```text
[23 81 14 56 92]
```

Random numbers are commonly used in Machine Learning, Data Science, Simulations, Testing and Model initialization.

### Seeds & reproducibility

In [47]:
np.random.seed(42)
print(np.random.randint(1, 100, 5))
print(np.random.rand(3))          # random floats in [0, 1)
print(np.random.rand(2, 3))       # random 2D array

np.random.seed(42)                # same seed -> same numbers
print(np.random.randint(1, 100, 5))

[52 93 15 72 61]
[0.59685016 0.44583275 0.09997492]
[[0.45924889 0.33370861 0.14286682]
 [0.65088847 0.05641158 0.72199877]]
[52 93 15 72 61]


---
# 🧮 Linear Algebra

NumPy also provides tools for mathematical and matrix operations, including matrix multiplication, dot product, transpose, determinant, inverse, eigenvalues and eigenvectors.

In [48]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

result = np.matmul(a, b)

print(result)

[[19 22]
 [43 50]]


In [49]:
print("Dot product  :", np.dot(np.array([1, 2, 3]), np.array([4, 5, 6])))
print("Determinant  :", np.linalg.det(a))
print("Inverse      :\n", np.linalg.inv(a))
vals, vecs = np.linalg.eig(a)
print("Eigenvalues  :", vals)
print("Eigenvectors :\n", vecs)

Dot product  : 32
Determinant  : -2.0000000000000004
Inverse      :
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues  : [-0.37228132+0.j  5.37228132+0.j]
Eigenvectors :
 [[-0.82456484+0.j -0.41597356+0.j]
 [ 0.56576746+0.j -0.90937671+0.j]]


---
# 🧹 Handling Numerical Data

NumPy can also be used for basic data preparation. It provides functions that help identify and work with numerical data issues.

In [50]:
data = np.array([10, 20, np.nan, 40, 50])

print(np.isnan(data))
print("Mean ignoring NaN:", np.nanmean(data))

# Replace missing value with the mean of the others
clean = np.where(np.isnan(data), np.nanmean(data), data)
print(clean)

[False False  True False False]
Mean ignoring NaN: 30.0
[10. 20. 30. 40. 50.]


### Normalization & Standardization

In [51]:
x = np.array([10., 20., 30., 40., 50.])

normalized   = (x - x.min()) / (x.max() - x.min())   # scale to 0..1
standardized = (x - x.mean()) / x.std()              # mean 0, std 1

print(normalized)
print(standardized)

[0.   0.25 0.5  0.75 1.  ]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


---
# 🤖 NumPy in Machine Learning

NumPy is one of the foundations of Machine Learning.

```text
Numbers → Arrays → Matrices → Vectors → Numerical Operations → Machine Learning
```

For example, a dataset can be represented as:

In [52]:
X = np.array([
    [20, 50000],
    [25, 60000],
    [30, 75000],
    [35, 90000]
])

print(X)
print("Samples :", X.shape[0])
print("Features:", X.shape[1])

[[   20 50000]
 [   25 60000]
 [   30 75000]
 [   35 90000]]
Samples : 4
Features: 2


Here:

```text
Rows    → Samples
Columns → Features
```

This idea will become important when learning Machine Learning.

---
# 🧠 NumPy in Deep Learning

Deep Learning frameworks such as PyTorch and TensorFlow work heavily with numerical arrays/tensors.

```text
NumPy Arrays → Numerical Data → Tensors → Neural Networks → Deep Learning
```

Understanding NumPy therefore makes later numerical and tensor operations easier to understand.

---
# 🌍 Real-World Uses of NumPy

* Data Science
* Machine Learning
* Deep Learning
* Scientific Computing
* Statistics
* Numerical Analysis
* Image Processing
* Signal Processing
* Financial Analysis
* Engineering
* Simulations
* Data Preprocessing

---
# 🛠️ Practical Examples

### Student Marks
```text
Student scores → NumPy Array → Mean → Maximum → Minimum → Statistics
```

In [53]:
marks = np.array([78, 85, 92, 67, 88])
print("Mean:", marks.mean(), "| Max:", marks.max(), "| Min:", marks.min())

Mean: 82.0 | Max: 92 | Min: 67


### Sales Data
```text
Daily sales → NumPy Array → Total → Average → Highest → Lowest
```

In [54]:
sales = np.array([1200, 1500, 900, 2000, 1750, 1100, 1600])
print("Total:", sales.sum(), "| Avg:", sales.mean(), "| High:", sales.max(), "| Low:", sales.min())

Total: 10050 | Avg: 1435.7142857142858 | High: 2000 | Low: 900


### Machine Learning Dataset
```text
Features → NumPy Array → Data preprocessing → Model input
```

---
# 📋 NumPy Important Functions

| Function           | Purpose                        |
| ------------------ | ------------------------------ |
| `np.array()`       | Create an array                |
| `np.zeros()`       | Create zeros                   |
| `np.ones()`        | Create ones                    |
| `np.full()`        | Fill with a value              |
| `np.arange()`      | Create a range                 |
| `np.linspace()`    | Create evenly spaced values    |
| `np.reshape()`     | Change array shape             |
| `np.concatenate()` | Join arrays                    |
| `np.split()`       | Split arrays                   |
| `np.sort()`        | Sort values                    |
| `np.where()`       | Find values based on condition |
| `np.sum()`         | Calculate total                |
| `np.mean()`        | Calculate average              |
| `np.median()`      | Calculate median               |
| `np.min()`         | Find minimum                   |
| `np.max()`         | Find maximum                   |
| `np.std()`         | Standard deviation             |
| `np.var()`         | Variance                       |
| `np.sqrt()`        | Square root                    |
| `np.abs()`         | Absolute value                 |
| `np.random`        | Generate random values         |

---
# 🧠 Important NumPy Concepts

```text
NumPy
│
├── Arrays
│   ├── 1D
│   ├── 2D
│   └── Multi-dimensional
│
├── Array Properties
│   ├── ndim
│   ├── shape
│   ├── size
│   └── dtype
│
├── Indexing
├── Slicing
├── Data Types
├── Array Creation
├── Mathematical Operations
├── Statistical Operations
├── Broadcasting
├── Reshaping
├── Joining
├── Splitting
├── Sorting
├── Filtering
├── Random Numbers
├── Copy & View
└── Linear Algebra
```

---
# 🎯 Learning Goals

After completing NumPy, I should be able to:

* Understand what NumPy is.
* Explain why NumPy is used.
* Create NumPy arrays.
* Understand dimensions and shapes.
* Access array elements.
* Slice arrays.
* Change array shapes.
* Perform mathematical operations.
* Perform statistical calculations.
* Filter numerical data.
* Understand broadcasting.
* Generate random data.
* Perform basic matrix operations.
* Work with numerical datasets.
* Prepare numerical data for Machine Learning.
* Understand the relationship between arrays, matrices, and numerical computing.

---
# 💼 Interview Questions

After completing this section, I should be able to answer:

### Beginner
1. What is NumPy?
2. What does NumPy stand for?
3. Why is NumPy used in Data Science?
4. What is a NumPy array?
5. What is `ndarray`?
6. What is the difference between a Python list and NumPy array?
7. What is `ndim`?
8. What is `shape`?
9. What is `size`?
10. What is `dtype`?

### Intermediate
11. What is broadcasting?
12. What is vectorization?
13. What is the difference between `reshape()` and `resize()`?
14. What is the difference between `flatten()` and `ravel()`?
15. What is the difference between a copy and a view?
16. How does Boolean filtering work?
17. How do you combine NumPy arrays?
18. How do you split NumPy arrays?
19. How do you generate random numbers using NumPy?
20. How is NumPy used in Machine Learning?

### Advanced Foundation
21. How does NumPy improve numerical computation?
22. What are NumPy axes?
23. How do operations work along an axis?
24. How does broadcasting work internally?
25. Why are NumPy operations generally faster than Python loops for numerical data?
26. What is vectorization?
27. How are NumPy arrays stored in memory?
28. What is the relationship between NumPy arrays and tensors?

---
# 📝 Practice Exercises

After learning each concept, practice with real examples. Write your solution in the code cell under each exercise.

### Exercise 01 — Basic Array

Create an array containing:

```text
10, 20, 30, 40, 50
```

Find:

* Number of elements
* Data type
* Number of dimensions
* Shape

### Exercise 02 — Student Marks

Create an array:

```text
[78, 85, 92, 67, 88, 95, 73]
```

Calculate:

* Total marks
* Average marks
* Highest marks
* Lowest marks
* Standard deviation

### Exercise 03 — Sales Data

Create daily sales data and calculate:

* Total sales
* Average sales
* Highest sales
* Lowest sales
* Days with sales above the average

### Exercise 04 — Matrix

Create a `3 × 3` matrix and practice:

* Indexing
* Slicing
* Transpose
* Sum
* Mean
* Maximum
* Minimum

### Exercise 05 — Boolean Filtering

Create an array of numbers and return:

* Numbers greater than 50
* Numbers less than 50
* Even numbers
* Odd numbers

### Exercise 06 — Reshaping

Create numbers from `1` to `12`.

Convert them into:

```text
2 × 6
3 × 4
4 × 3
6 × 2
```

### Exercise 07 — Broadcasting

Create an array of prices and increase every price by:

```text
10%
```

### Exercise 08 — Mini Data Science Project

Create a small numerical dataset containing:

```text
Student
Age
Study Hours
Marks
```

Use NumPy to calculate:

* Average age
* Average study hours
* Average marks
* Highest marks
* Lowest marks
* Students above average
* Relationship between study hours and marks