## Chapter 1: Why NumPy?

A Python `list` stores pointers to separate `PyObject`s scattered across memory, so every element access involves pointer chasing and type checks. A NumPy `ndarray` stores raw values of a single type in one **contiguous memory block**, accessed via C pointers, and operations run in compiled C code. The benchmark below compares both on 1,000,000 items.

In [2]:
import numpy as np
import time

# Benchmark: Standard Python Lists vs. NumPy Vectorization
size = 1_000_000

# 1. Standard Python Lists
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
list_result = [x + y for x, y in zip(list1, list2)]
python_time = time.time() - start_time

# 2. NumPy Vectorized Operation
arr1 = np.arange(size)
arr2 = np.arange(size)

start_time = time.time()
numpy_result = arr1 + arr2
numpy_time = time.time() - start_time

print(f"Python List Execution Time: {python_time:.5f} seconds")
print(f"NumPy Array Execution Time:  {numpy_time:.5f} seconds")
print(f"⚡ NumPy is {python_time / numpy_time:.2f}x faster!")

Python List Execution Time: 0.11191 seconds
NumPy Array Execution Time:  0.02641 seconds
⚡ NumPy is 4.24x faster!


## Chapter 2: Array Initialization & `dtypes`

In [3]:
# 1D Vector, 2D Matrix, and 3D Tensor
vec = np.array([10, 20, 30, 40, 50], dtype=np.int64)
mat = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)

# High-level initializers
zeros_arr = np.zeros((2, 3))
ones_arr = np.ones((3, 3), dtype=np.int32)
range_arr = np.arange(10, 50, 5)            # Start: 10, Stop: 50, Step: 5
linspace_arr = np.linspace(0, 1, 5)         # 5 evenly spaced points from 0 to 1
identity_mat = np.eye(3)                    # 3x3 Identity Matrix

print("Linspace Array:", linspace_arr)
print("3x3 Identity Matrix:\n", identity_mat)

Linspace Array: [0.   0.25 0.5  0.75 1.  ]
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Chapter 3: Deep Inspection Attributes

In [4]:
sample_tensor = np.ones((2, 3, 4), dtype=np.float64)

print(f"Shape (Dimensions):      {sample_tensor.shape}")
print(f"Number of Axes (ndim):   {sample_tensor.ndim}")
print(f"Data Type (dtype):       {sample_tensor.dtype}")
print(f"Total Elements (size):   {sample_tensor.size}")
print(f"Bytes per Item:          {sample_tensor.itemsize}")
print(f"Total Memory Consumption: {sample_tensor.nbytes} bytes")

Shape (Dimensions):      (2, 3, 4)
Number of Axes (ndim):   3
Data Type (dtype):       float64
Total Elements (size):   24
Bytes per Item:          8
Total Memory Consumption: 192 bytes


## Chapter 4: Slicing, Fancy Indexing & Masking

In [5]:
data = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

# Sub-matrix slicing [row_slice, col_slice]
sub_matrix = data[:2, 1:3]
print("Sub-matrix (Rows 0-1, Cols 1-2):\n", sub_matrix)

# Boolean Masking (In-place filtering without slow loops)
scores = np.array([85, 42, 90, 68, 55, 30])
passing_scores = scores[scores >= 60]
print("Passing Scores:", passing_scores)

# Modifying values directly using Boolean conditions
scores[scores < 60] = 0
print("Scores with failures zeroed out:", scores)

Sub-matrix (Rows 0-1, Cols 1-2):
 [[20 30]
 [60 70]]
Passing Scores: [85 90 68]
Scores with failures zeroed out: [85  0 90 68  0  0]


## Chapter 5: Broadcasting & Matrix Math

In [6]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

vector = np.array([10, 20, 30])

# Broadcasting: vector stretches automatically to match matrix dimensions
broadcast_sum = matrix + vector
print("Broadcasted Addition Result:\n", broadcast_sum)

# Axis-wise Aggregations
print("Overall Mean:", np.mean(matrix))
print("Column-wise Sums (axis=0):", np.sum(matrix, axis=0))
print("Row-wise Sums (axis=1):", np.sum(matrix, axis=1))

Broadcasted Addition Result:
 [[11 22 33]
 [14 25 36]]
Overall Mean: 3.5
Column-wise Sums (axis=0): [5 7 9]
Row-wise Sums (axis=1): [ 6 15]


## Chapter 6: Reshaping, Transpose & Linear Algebra

In [7]:
arr = np.arange(1, 7)
reshaped = arr.reshape((2, 3))
transposed = reshaped.T

print("Reshaped Matrix (2x3):\n", reshaped)
print("Transposed Matrix (3x2):\n", transposed)

# Linear Algebra Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

product = A @ B  # Modern shorthand for np.dot(A, B)
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)

print("Matrix Product (A @ B):\n", product)
print(f"Determinant of A: {det_A:.2f}")
print("Inverse Matrix of A:\n", inv_A)

Reshaped Matrix (2x3):
 [[1 2 3]
 [4 5 6]]
Transposed Matrix (3x2):
 [[1 4]
 [2 5]
 [3 6]]
Matrix Product (A @ B):
 [[19 22]
 [43 50]]
Determinant of A: -2.00
Inverse Matrix of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## Chapter 7: Random Sampling & Reproducibility

In [8]:
# Set Seed for exact experiment reproducibility across runs
np.random.seed(42)

uniform_sample = np.random.rand(3)              # Uniform distribution [0, 1)
normal_sample = np.random.randn(2, 3)           # Gaussian distribution (mean=0, std=1)
int_sample = np.random.randint(1, 100, 5)       # 5 random integers from 1 to 99

print("Normal Distribution Sample:\n", normal_sample)
print("Random Integers:", int_sample)

Normal Distribution Sample:
 [[-1.11188012  0.31890218  0.27904129]
 [ 1.01051528 -0.58087813 -0.52516981]]
Random Integers: [21 33 76 58 22]
